console.log(1 === '1');
console.log(true === 1);
console.log(null === undefined);
console.log('' === false);
console.log(NaN === NaN);
// console.log([1, 2, 3] === [1, 2, 3]);
console.log('hello' === 'hello');
// console.log([] === []);
console.log(true == 1);
console.log(1 == '1');
console.log(null == undefined);
console.log('' == false);
console.log('0' == false);
console.log([1, 2, 3] == '1,2,3');
console.log([] == false);
console.log(null == 0);
console.log(null == false);
console.log([0] == false);
console.log([null] == false);
console.log([1, {}, 3] == '1,{},3');
// console.log([1, {name: 'sagar'}, 3] == [1, {name: 'sagar'}, 3]);
