console.log(1, 1 === '1');
console.log(2, true === 1);
console.log(3, null === undefined);
console.log(4, '' === false);
console.log(5, NaN === NaN);
// console.log(6, [1, 2, 3] === [1, 2, 3]);
console.log(7, 'hello' === 'hello');
// console.log(8, [] === []);
console.log(9, true == 1);
// console.log(10, 1 == '1');
console.log(11, null == undefined);
console.log(12, '' == false);
console.log(13, '0' == false);
console.log(14, [1, 2, 3] == '1,2,3');
// console.log(15, [] == false);
console.log(16, null == 0);
console.log(17, null == false);
console.log(18, [0] == false);
console.log(19, [null] == false);
console.log(20, [1, {}, 3] == '1,{},3');
// console.log(21, [1, {name: 'sagar'}, 3] == [1, {name: 'sagar'}, 3]);
